site_name: postmodal
repo_url: https://github.com/runlevel0/postmodal
site_url: https://runlevel0.github.io/postmodal
site_description: Postprocessing of modal parameters from structural dynamics.
site_author: Patrick Simon
edit_uri: edit/main/docs/
repo_name: runlevel0/postmodal
copyright: Maintained by Patrick Simon.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fpgmaas/example-project
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/example-project

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
